<?php

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create(['prefix' => '93', 'name' => 'Afghanistan']);
        Country::create(['prefix' => '355', 'name' => 'Albania']);
        Country::create(['prefix' => '213', 'name' => 'Algeria']);
        Country::create(['prefix' => '1684', 'name' => 'American Samoa']);
        Country::create(['prefix' => '376', 'name' => 'Andorra']);
        Country::create(['prefix' => '244', 'name' => 'Angola']);
        Country::create(['prefix' => '1264', 'name' => 'Anguilla']);
        Country::create(['prefix' => '672', 'name' => 'Antarctica']);
        Country::create(['prefix' => '1268', 'name' => 'Antigua and Barbuda']);
        Country::create(['prefix' => '54', 'name' => 'Argentina']);
        Country::create(['prefix' => '374', 'name' => 'Armenia']);
        Country::create(['prefix' => '297', 'name' => 'Aruba']);
        Country::create(['prefix' => '61', 'name' => 'Australia']);
        Country::create(['prefix' => '43', 'name' => 'Austria']);
        Country::create(['prefix' => '994', 'name' => 'Azerbaijan']);
        Country::create(['prefix' => '1242', 'name' => 'Bahamas']);
        Country::create(['prefix' => '973', 'name' => 'Bahrain']);
        Country::create(['prefix' => '880', 'name' => 'Bangladesh']);
        Country::create(['prefix' => '1246', 'name' => 'Barbados']);
        Country::create(['prefix' => '375', 'name' => 'Belarus']);
        Country::create(['prefix' => '32', 'name' => 'Belgium']);
        Country::create(['prefix' => '501', 'name' => 'Belize']);
        Country::create(['prefix' => '229', 'name' => 'Benin']);
        Country::create(['prefix' => '1441', 'name' => 'Bermuda']);
        Country::create(['prefix' => '975', 'name' => 'Bhutan']);
        Country::create(['prefix' => '591', 'name' => 'Bolivia']);
        Country::create(['prefix' => '599', 'name' => 'Bonaire']);
        Country::create(['prefix' => '387', 'name' => 'Bosnia and Herzegovina']);
        Country::create(['prefix' => '267', 'name' => 'Botswana']);
        Country::create(['prefix' => '47', 'name' => 'Bouvet Island']);
        Country::create(['prefix' => '55', 'name' => 'Brazil']);
        Country::create(['prefix' => '1284', 'name' => 'British Virgin Islands']);
        Country::create(['prefix' => '246', 'name' => 'British indian ocean territory']);
        Country::create(['prefix' => '673', 'name' => 'Brunei Darussalam']);
        Country::create(['prefix' => '359', 'name' => 'Bulgaria']);
        Country::create(['prefix' => '226', 'name' => 'Burkina Faso']);
        Country::create(['prefix' => '257', 'name' => 'Burundi']);
        Country::create(['prefix' => '855', 'name' => 'Cambodia']);
        Country::create(['prefix' => '237', 'name' => 'Cameroon']);
        Country::create(['prefix' => '1', 'name' => 'Canada']);
        Country::create(['prefix' => '238', 'name' => 'Cape Verde']);
        Country::create(['prefix' => '1345', 'name' => 'Cayman Islands']);
        Country::create(['prefix' => '236', 'name' => 'Central African Republic']);
        Country::create(['prefix' => '235', 'name' => 'Chad']);
        Country::create(['prefix' => '56', 'name' => 'Chile']);
        Country::create(['prefix' => '86', 'name' => 'China']);
        Country::create(['prefix' => '61', 'name' => 'Christmas Island']);
        Country::create(['prefix' => '61', 'name' => 'Cocos Islands']);
        Country::create(['prefix' => '57', 'name' => 'Colombia']);
        Country::create(['prefix' => '269', 'name' => 'Comoros']);
        Country::create(['prefix' => '242', 'name' => 'Congo']);
        Country::create(['prefix' => '682', 'name' => 'Cook Islands']);
        Country::create(['prefix' => '506', 'name' => 'Costa Rica']);
        // Country::create(['prefix' => '225', 'name' => 'Cote d'Ivoire (Ivory Coast)']);
        Country::create(['prefix' => '385', 'name' => 'Croatia']);
        Country::create(['prefix' => '53', 'name' => 'Cuba']);
        Country::create(['prefix' => '599', 'name' => 'Curacao']);
        Country::create(['prefix' => '357', 'name' => 'Cyprus']);
        Country::create(['prefix' => '420', 'name' => 'Czech Republic']);
        Country::create(['prefix' => '243', 'name' => 'Democratic Republic of the Congo']);
        Country::create(['prefix' => '45', 'name' => 'Denmark']);
        Country::create(['prefix' => '253', 'name' => 'Djibouti']);
        Country::create(['prefix' => '1767', 'name' => 'Dominica']);
        Country::create(['prefix' => '1809', 'name' => 'Dominican Republic']);
        Country::create(['prefix' => '593', 'name' => 'Ecuador']);
        Country::create(['prefix' => '20', 'name' => 'Egypt']);
        Country::create(['prefix' => '503', 'name' => 'El Salvador']);
        Country::create(['prefix' => '240', 'name' => 'Equatorial Guinea']);
        Country::create(['prefix' => '291', 'name' => 'Eritrea']);
        Country::create(['prefix' => '372', 'name' => 'Estonia']);
        Country::create(['prefix' => '251', 'name' => 'Ethiopia']);
        Country::create(['prefix' => '500', 'name' => 'Falkland Islands (Malvinas)']);
        Country::create(['prefix' => '298', 'name' => 'Faroe Islands']);
        Country::create(['prefix' => '691', 'name' => 'Federated States of Micronesia']);
        Country::create(['prefix' => '679', 'name' => 'Fiji']);
        Country::create(['prefix' => '358', 'name' => 'Finland']);
        Country::create(['prefix' => '33', 'name' => 'France']);
        Country::create(['prefix' => '594', 'name' => 'French Guiana']);
        Country::create(['prefix' => '689', 'name' => 'French Polynesia']);
        Country::create(['prefix' => '262', 'name' => 'French Southern Territories']);
        Country::create(['prefix' => '241', 'name' => 'Gabon']);
        Country::create(['prefix' => '220', 'name' => 'Gambia']);
        Country::create(['prefix' => '995', 'name' => 'Georgia']);
        Country::create(['prefix' => '49', 'name' => 'Germany']);
        Country::create(['prefix' => '233', 'name' => 'Ghana']);
        Country::create(['prefix' => '350', 'name' => 'Gibraltar']);
        Country::create(['prefix' => '30', 'name' => 'Greece']);
        Country::create(['prefix' => '299', 'name' => 'Greenland']);
        Country::create(['prefix' => '1473', 'name' => 'Grenada']);
        Country::create(['prefix' => '590', 'name' => 'Guadeloupe']);
        Country::create(['prefix' => '1671', 'name' => 'Guam']);
        Country::create(['prefix' => '502', 'name' => 'Guatemala']);
        Country::create(['prefix' => '441481', 'name' => 'Guernsey']);
        Country::create(['prefix' => '224', 'name' => 'Guinea']);
        Country::create(['prefix' => '245', 'name' => 'Guinea-Bissau']);
        Country::create(['prefix' => '592', 'name' => 'Guyana']);
        Country::create(['prefix' => '509', 'name' => 'Haiti']);
        Country::create(['prefix' => '61', 'name' => 'Heard Island and McDonald Islands']);
        Country::create(['prefix' => '504', 'name' => 'Honduras']);
        Country::create(['prefix' => '852', 'name' => 'Hong Kong']);
        Country::create(['prefix' => '36', 'name' => 'Hungary']);
        Country::create(['prefix' => '354', 'name' => 'Iceland']);
        Country::create(['prefix' => '91', 'name' => 'India']);
        Country::create(['prefix' => '62', 'name' => 'Indonesia']);
        Country::create(['prefix' => '98', 'name' => 'Iran']);
        Country::create(['prefix' => '964', 'name' => 'Iraq']);
        Country::create(['prefix' => '353', 'name' => 'Ireland']);
        Country::create(['prefix' => '441624', 'name' => 'Isle of Man']);
        Country::create(['prefix' => '972', 'name' => 'Israel']);
        Country::create(['prefix' => '39', 'name' => 'Italy']);
        Country::create(['prefix' => '1876', 'name' => 'Jamaica']);
        Country::create(['prefix' => '81', 'name' => 'Japan']);
        Country::create(['prefix' => '441534', 'name' => 'Jersey']);
        Country::create(['prefix' => '962', 'name' => 'Jordan']);
        Country::create(['prefix' => '7', 'name' => 'Kazakhstan']);
        Country::create(['prefix' => '254', 'name' => 'Kenya']);
        Country::create(['prefix' => '686', 'name' => 'Kiribati']);
        Country::create(['prefix' => '965', 'name' => 'Kuwait']);
        Country::create(['prefix' => '996', 'name' => 'Kyrgyzstan']);
        Country::create(['prefix' => '856', 'name' => 'Laos']);
        Country::create(['prefix' => '371', 'name' => 'Latvia']);
        Country::create(['prefix' => '961', 'name' => 'Lebanon']);
        Country::create(['prefix' => '266', 'name' => 'Lesotho']);
        Country::create(['prefix' => '231', 'name' => 'Liberia']);
        Country::create(['prefix' => '218', 'name' => 'Libya']);
        Country::create(['prefix' => '423', 'name' => 'Liechtenstein']);
        Country::create(['prefix' => '370', 'name' => 'Lithuania']);
        Country::create(['prefix' => '352', 'name' => 'Luxembourg']);
        Country::create(['prefix' => '853', 'name' => 'Macao']);
        Country::create(['prefix' => '389', 'name' => 'Macedonia']);
        Country::create(['prefix' => '261', 'name' => 'Madagascar']);
        Country::create(['prefix' => '265', 'name' => 'Malawi']);
        Country::create(['prefix' => '60', 'name' => 'Malaysia']);
        Country::create(['prefix' => '960', 'name' => 'Maldives']);
        Country::create(['prefix' => '223', 'name' => 'Mali']);
        Country::create(['prefix' => '356', 'name' => 'Malta']);
        Country::create(['prefix' => '692', 'name' => 'Marshall Islands']);
        Country::create(['prefix' => '596', 'name' => 'Martinique']);
        Country::create(['prefix' => '222', 'name' => 'Mauritania']);
        Country::create(['prefix' => '230', 'name' => 'Mauritius']);
        Country::create(['prefix' => '262', 'name' => 'Mayotte']);
        Country::create(['prefix' => '52', 'name' => 'Mexico']);
        Country::create(['prefix' => '373', 'name' => 'Moldova']);
        Country::create(['prefix' => '377', 'name' => 'Monaco']);
        Country::create(['prefix' => '976', 'name' => 'Mongolia']);
        Country::create(['prefix' => '382', 'name' => 'Montenegro']);
        Country::create(['prefix' => '1664', 'name' => 'Montserrat']);
        Country::create(['prefix' => '212', 'name' => 'Morocco']);
        Country::create(['prefix' => '258', 'name' => 'Mozambique']);
        Country::create(['prefix' => '95', 'name' => 'Myanmar (Burma)']);
        Country::create(['prefix' => '264', 'name' => 'Namibia']);
        Country::create(['prefix' => '674', 'name' => 'Nauru']);
        Country::create(['prefix' => '977', 'name' => 'Nepal']);
        Country::create(['prefix' => '599', 'name' => 'Netherlands Antilles']);
        Country::create(['prefix' => '31', 'name' => 'Netherlands']);
        Country::create(['prefix' => '687', 'name' => 'New Caledonia']);
        Country::create(['prefix' => '64', 'name' => 'New Zealand']);
        Country::create(['prefix' => '505', 'name' => 'Nicaragua']);
        Country::create(['prefix' => '227', 'name' => 'Niger']);
        Country::create(['prefix' => '234', 'name' => 'Nigeria']);
        Country::create(['prefix' => '683', 'name' => 'Niue']);
        Country::create(['prefix' => '672', 'name' => 'Norfolk Island']);
        Country::create(['prefix' => '850', 'name' => 'North Korea']);
        Country::create(['prefix' => '1670', 'name' => 'Northern Mariana Islands']);
        Country::create(['prefix' => '47', 'name' => 'Norway']);
        Country::create(['prefix' => '968', 'name' => 'Oman']);
        Country::create(['prefix' => '92', 'name' => 'Pakistan']);
        Country::create(['prefix' => '680', 'name' => 'Palau']);
        Country::create(['prefix' => '970', 'name' => 'Palestine']);
        Country::create(['prefix' => '507', 'name' => 'Panama']);
        Country::create(['prefix' => '675', 'name' => 'Papua New Guinea']);
        Country::create(['prefix' => '595', 'name' => 'Paraguay']);
        Country::create(['prefix' => '51', 'name' => 'Peru']);
        Country::create(['prefix' => '63', 'name' => 'Philippines']);
        Country::create(['prefix' => '64', 'name' => 'Pitcairn']);
        Country::create(['prefix' => '48', 'name' => 'Poland']);
        Country::create(['prefix' => '351', 'name' => 'Portugal']);
        Country::create(['prefix' => '1787', 'name' => 'Puerto Rico']);
        Country::create(['prefix' => '974', 'name' => 'Qatar']);
        Country::create(['prefix' => '262', 'name' => 'Reunion']);
        Country::create(['prefix' => '40', 'name' => 'Romania']);
        Country::create(['prefix' => '7', 'name' => 'Russian Federation']);
        Country::create(['prefix' => '250', 'name' => 'Rwanda']);
        Country::create(['prefix' => '590', 'name' => 'Saint Barthelemy']);
        Country::create(['prefix' => '290', 'name' => 'Saint Helena']);
        Country::create(['prefix' => '1869', 'name' => 'Saint Kitts and Nevis']);
        Country::create(['prefix' => '1758', 'name' => 'Saint Lucia']);
        Country::create(['prefix' => '590', 'name' => 'Saint Martin']);
        Country::create(['prefix' => '508', 'name' => 'Saint Pierre And Miquelon']);
        Country::create(['prefix' => '1784', 'name' => 'Saint Vincent and the Grenadines']);
        Country::create(['prefix' => '685', 'name' => 'Samoa']);
        Country::create(['prefix' => '378', 'name' => 'San Marino']);
        Country::create(['prefix' => '239', 'name' => 'Sao Tome and Principe']);
        Country::create(['prefix' => '966', 'name' => 'Saudi Arabia']);
        Country::create(['prefix' => '221', 'name' => 'Senegal']);
        Country::create(['prefix' => '381', 'name' => 'Serbia']);
        Country::create(['prefix' => '248', 'name' => 'Seychelles']);
        Country::create(['prefix' => '232', 'name' => 'Sierra Leone']);
        Country::create(['prefix' => '65', 'name' => 'Singapore']);
        Country::create(['prefix' => '590', 'name' => 'Sint Maarten (Dutch Part)']);
        Country::create(['prefix' => '421', 'name' => 'Slovakia']);
        Country::create(['prefix' => '386', 'name' => 'Slovenia']);
        Country::create(['prefix' => '677', 'name' => 'Solomon Islands']);
        Country::create(['prefix' => '252', 'name' => 'Somalia']);
        Country::create(['prefix' => '27', 'name' => 'South Africa']);
        Country::create(['prefix' => '500', 'name' => 'South Georgia And The South Sandwich Islands']);
        Country::create(['prefix' => '82', 'name' => 'South Korea']);
        Country::create(['prefix' => '34', 'name' => 'Spain']);
        Country::create(['prefix' => '94', 'name' => 'Sri Lanka']);
        Country::create(['prefix' => '249', 'name' => 'Sudan']);
        Country::create(['prefix' => '597', 'name' => 'Suriname']);
        Country::create(['prefix' => '47', 'name' => 'Svalbard']);
        Country::create(['prefix' => '268', 'name' => 'Swaziland']);
        Country::create(['prefix' => '46', 'name' => 'Sweden']);
        Country::create(['prefix' => '41', 'name' => 'Switzerland']);
        Country::create(['prefix' => '963', 'name' => 'Syrian Arab Republic']);
        Country::create(['prefix' => '886', 'name' => 'Taiwan']);
        Country::create(['prefix' => '992', 'name' => 'Tajikistan']);
        Country::create(['prefix' => '255', 'name' => 'Tanzania']);
        Country::create(['prefix' => '66', 'name' => 'Thailand']);
        Country::create(['prefix' => '670', 'name' => 'Timor-Leste (East Timor)']);
        Country::create(['prefix' => '228', 'name' => 'Togo']);
        Country::create(['prefix' => '690', 'name' => 'Tokelau']);
        Country::create(['prefix' => '676', 'name' => 'Tonga']);
        Country::create(['prefix' => '1867', 'name' => 'Trinidad and Tobago']);
        Country::create(['prefix' => '216', 'name' => 'Tunisia']);
        Country::create(['prefix' => '90', 'name' => 'Turkey']);
        Country::create(['prefix' => '993', 'name' => 'Turkmenistan']);
        Country::create(['prefix' => '1649', 'name' => 'Turks and Caicos Islands']);
        Country::create(['prefix' => '688', 'name' => 'Tuvalu']);
        Country::create(['prefix' => '1340', 'name' => 'U.S. Virgin Islands']);
        Country::create(['prefix' => '256', 'name' => 'Uganda']);
        Country::create(['prefix' => '380', 'name' => 'Ukraine']);
        Country::create(['prefix' => '971', 'name' => 'United Arab Emirates']);
        Country::create(['prefix' => '44', 'name' => 'United Kingdom']);
        Country::create(['prefix' => '1', 'name' => 'United States']);
        Country::create(['prefix' => '598', 'name' => 'Uruguay']);
        Country::create(['prefix' => '998', 'name' => 'Uzbekistan']);
        Country::create(['prefix' => '678', 'name' => 'Vanuatu']);
        Country::create(['prefix' => '379', 'name' => 'Vatican']);
        Country::create(['prefix' => '58', 'name' => 'Venezuela']);
        Country::create(['prefix' => '84', 'name' => 'Vietnam']);
        Country::create(['prefix' => '681', 'name' => 'Wallis and Futuna']);
        Country::create(['prefix' => '212', 'name' => 'Western Sahara']);
        Country::create(['prefix' => '967', 'name' => 'Yemen']);
        Country::create(['prefix' => '260', 'name' => 'Zambia']);
        Country::create(['prefix' => '263', 'name' => 'Zimbabwe']);
    }
}
